#!/usr/bin/env bash

#         DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                 Version 2, December 2004
#
# Copyright 2016 yourname
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#         DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
# TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.


. "$HOME/.cache/wal/colors.sh"

format="%title% - %album%"

fa_playing=""
fa_paused=""
fa_stopped=""

playing_color="$color4"
paused_color="$color2"
stopped_color="$color1"


player="$BLOCK_INSTANCE"
if [[ ( -z "$(pgrep -a $player)" ) || ( -z "$player" ) ]]; then
    exit 0
fi

if [[ -n "$BLOCK_BUTTON"  ]]; then
    if [[ "$BLOCK_BUTTON" == "1" ]]; then
        playerctl -p "$player" play-pause > /dev/null 2>&1
    elif [[ "$BLOCK_BUTTON" == "2" ]]; then
        playerctl -p "$player" previous > /dev/null 2>&1
    elif [[ "$BLOCK_BUTTON" == "3" ]]; then
        playerctl -p "$player" next > /dev/null 2>&1
    fi
fi

status=$(playerctl -p "$player" status)

if [[ "$status" = "Stopped" ]]; then
    echo "$fa_stopped $player is stopped"
    echo
    echo "$stopped_color"
    exit 0
elif [[ "$status" == "Playing" ]]; then
    icon="$fa_playing"
    color="$playing_color"
else
    icon="$fa_paused"
    color="$paused_color"
fi

current="$(playerctl -p "$player" metadata title) - $(playerctl -p "$player" metadata album)"

echo "$icon $current"
echo
echo "$color"
exit 0
